name: Call-Patchworks-Api

on:
  issue_comment:
    types: [created]

jobs:
  ping-api:
    if: ${{ contains(github.event.comment.body, '/ping') && (github.event.comment.user.login == 'ewlu' || github.event.comment.user.login == 'patrick-rivos') }}
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Bump pyopenssl and crypto
        run: |
          sudo apt remove python3-pip
          wget https://bootstrap.pypa.io/get-pip.py
          sudo python3 get-pip.py
          pip install -U pyopenssl cryptography
          pip install requests

      - name: Report Warning
        if: contains(github.event.issue.labels.*.name, 'build-only')
        run: |
          echo WARN 

      - name: Report Error
        if: contains(github.event.issue.labels.*.name, 'new-regressions')
        run: |
          echo ERROR 

      - name: Report Pass
        if: ${{ !contains(github.event.issue.labels.*.name, 'new-regressions') && !contains(github.event.issue.labels.*.name, 'build-only')
        run: |
          echo PASS 

        

