name: Lint

on:
  workflow_call:
    inputs:
      patch_name:
        required: true
        type: string
      sources_artifact:
        required: true
        type: string
      baseline_results_artifact:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Download patches artifact
        uses: actions/download-artifact@v3
        with:
          name: patches

      - name: Extract patches
        run: |
          echo TODO

      - name: Lint patch
        run: |
          python ./scripts/check_GNU_style.py ${{ inputs.patch_name }} | tee lint_results.txt
