name: Lint

on:
  workflow_call:
    inputs:
      patch_name:
        required: true
        type: string
      sources_artifact:
        required: true
        type: string
      baseline_results_artifact:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Download patches artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.patch_name }}-downloaded-patches

      - name: Extract patches
        run: |
          unzip ${{ inputs.patch_name }}-downloaded-patches.zip

      - name: Lint patch
        run: |
          let count=1
          for file in $(ls patches); do 
            python ./scripts/check_GNU_style.py "./patches/$file" | tee "lint_results_$count.txt"
            count=$(($count+1))
          done;
